FROM python:3.12.7-slim-bullseye
RUN mkdir /app
COPY ./discord-bot/requirements.txt /requirements.txt
RUN pip install -r requirements.txt
WORKDIR /app
COPY ./discord-bot /app
CMD ["python", "bot.py"]
